load("@bazel_skylib//rules:build_test.bzl", "build_test")
load("@bazel_skylib//rules:diff_test.bzl", "diff_test")
load("@bazel_skylib//rules:write_file.bzl", "write_file")
load("@msvc_runtime//:versions.bzl", "MSVC_COMPATIBILITY_VERSION", "MSVC_TOOLSET_VERSION", "VC_REDIST_VERSION")
load("@windows_sdk//:versions.bzl", "WINDOWS_SDK_INCLUDE_VERSION", "WINDOWS_SDK_VERSION")

alias(
    name = "configured_msvc_runtime_repo",
    actual = "@msvc_runtime//:all_files",
    tags = ["manual"],
)

alias(
    name = "configured_msvc_runtime_vc_redist",
    actual = "@msvc_runtime//:vc_redist",
    tags = ["manual"],
)

alias(
    name = "configured_windows_sdk_repo",
    actual = "@windows_sdk//:all_files",
    tags = ["manual"],
)

build_test(
    name = "smoke_test",
    targets = [
        ":configured_msvc_runtime_repo",
        ":configured_msvc_runtime_vc_redist",
        ":configured_windows_sdk_repo",
    ],
)

write_file(
    name = "resolved_versions",
    out = "resolved_versions.txt",
    content = [
        "MSVC_TOOLSET_VERSION={}".format(MSVC_TOOLSET_VERSION),
        "MSVC_COMPATIBILITY_VERSION={}".format(MSVC_COMPATIBILITY_VERSION),
        "VC_REDIST_VERSION={}".format(VC_REDIST_VERSION),
        "WINDOWS_SDK_VERSION={}".format(WINDOWS_SDK_VERSION),
        "WINDOWS_SDK_INCLUDE_VERSION={}".format(WINDOWS_SDK_INCLUDE_VERSION),
        "",
    ],
)

diff_test(
    name = "resolved_versions_test",
    file1 = "expected_versions.txt",
    file2 = ":resolved_versions",
)
